language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN="0ff229b7-f231-4fe5-8d18-42e9b4e208b4"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - voronovadaria@gmail.com
    on_success: never # default: change
    on_failure: always # default: always